### ISSUE TITLE
@Override?

### ISSUE THREAD

**Issue by KaeKen** [michaelangelosalvio/cpe50#1]
Anu ni sir? sa line 35. Item.java

**Comment by michaelangelosalvio** [comment]
``` java
@Override
public String toString() {
        return this.getProduct().getProductName() + "\t" + this.getQuantity() + "\t" + this.getProduct().getPrice() + "\t\t" + this.getAmount();
}
```

The override section stated above is a line that states that this method as inherited from the parent object. All objects inherits is method from the `Object` class.

Inheritance will be discussed on midterm. If ever you delete it, it would still work.
